#ER模型
-- 多对多的关系，需要中间表
-- 一对多的关系，通过外键表达

-- 强实体
-- 用户实体
CREATE TABLE `user_info`(
 `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
 `user_name` VARCHAR(200) DEFAULT NULL COMMENT '用户名称',
 `nick_name` VARCHAR(200) DEFAULT NULL COMMENT '用户昵称',
 `passwd` VARCHAR(200) DEFAULT NULL COMMENT '用户密码',
 `phone_num` VARCHAR(200) DEFAULT NULL COMMENT '手机号',
 `email` VARCHAR(200) DEFAULT NULL COMMENT '邮箱',
 `head_img` VARCHAR(200) DEFAULT NULL COMMENT '头像',
 `user_level` VARCHAR(200) DEFAULT NULL COMMENT '用户级别',
 PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='用户表';

-- 商品分类实体
-- 一级分类表
CREATE TABLE `base_category1`(
 `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
 `name` VARCHAR(10) NOT NULL COMMENT '分类名称',
 PRIMARY KEY(`id`) USING BTREE
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='一级分类表';

-- 二级分类表
CREATE TABLE `base_category2`(
 `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
 `name` VARCHAR(200) NOT NULL COMMENT '二级分类名称',
 `category1_id` BIGINT(20) DEFAULT NULL COMMENT '一级分类编号',
 PRIMARY KEY(`id`) USING BTREE
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='二级分类表';

